### hello

POST http://localhost:4414/applicant/apply-for-job
Content-Type: multipart/form-data

{
  "id:": "ce5e6c19-e362-4a0e-6d1c-069372cd67dc"
  "jobId": "414b041e-1219-4ea0-b7be-c48351c9e364",
  "applicanId": "ce5e6c19-e362-4a0e-6d1c-069372cd67dc"
}

###get

POST https://0z548vh3-4414.euw.devtunnels.ms/admin/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "admin"
}

### get pdf
POST  http://localhost:4414/applicant/applications
Content-Type: application/json

{
  "id": "ce5e6c19-e362-4a0e-6d1c-069372cd67dc"
}